### Get dotnet process list
GRPC localhost:5197/monitor.ProcessManager/GetProcessList

### Get dotnet process details
GRPC localhost:5197/monitor.ProcessManager/GetProcessDetails

{
  "process_id": {{process-id}}
}

### Get dotnet process environment variables
GRPC localhost:5197/monitor.ProcessManager/GetProcessEnvironment

{
  "process_id": {{process-id}}
}