### Get process list
GRPC localhost:5197/monitor.ProcessService/GetProcessList

### Get `DebugSamples` process
GRPC localhost:5197/monitor.ProcessService/GetProcessByName

{
  "process_name": "DebugSamples"
}

> {%
    client.global.set("process_id", response.body.process.processId);
%}

### Get process details
GRPC localhost:5197/monitor.ProcessService/GetProcessDetails

{
  "process_id": {{process_id}}
}

### Get process environment variables
GRPC localhost:5197/monitor.ProcessService/GetProcessEnvironment

{
  "process_id": {{process_id}}
}

### Get process counters
GRPC localhost:5197/monitor.CounterService/GetCounterStream

{
  "process_id": {{process_id}},
  "duration_in_seconds": 3
}

### Get process counters with non-default provider
GRPC localhost:5197/monitor.CounterService/GetCounterStream

{
  "process_id": {{process_id}},
  "duration_in_seconds": 10,
  "provider_name": "Microsoft.AspNetCore.Hosting"
}

### Collect process thread dump
GRPC localhost:5197/monitor.ThreadDumpService/CollectThreadDump

{
  "process_id": {{process_id}}
}

### Collect process memory dump
GRPC localhost:5197/monitor.MemoryDumpService/CollectMemoryDump

{
  "process_id": {{process_id}}
}

> {%
    client.global.set("memory_dump_id", response.body.memoryDumpId);
%}

### Delete process memory dump
GRPC localhost:5197/monitor.MemoryDumpService/DeleteMemoryDump

{
  "memory_dump_id": {{memory_dump_id}}
}

### Analyze CLR stack
GRPC localhost:5197/monitor.MemoryDumpService/AnalyzeClrStack

{
  "memory_dump_id": {{memory_dump_id}}
}